//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVChatbot.Bot.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NoItemsInFilterEntry
    {
        public int Id { get; set; }
        public string TagName { get; set; }
        public System.DateTimeOffset EntryTs { get; set; }
    
        public virtual RegisteredUser RegisteredUser { get; set; }
    }
}
