//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVChatbot.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReviewSession
    {
        public int Id { get; set; }
        public System.DateTimeOffset SessionStart { get; set; }
        public Nullable<System.DateTimeOffset> SessionEnd { get; set; }
        public Nullable<int> ItemsReviewed { get; set; }
    
        public virtual RegisteredUser RegisteredUser { get; set; }
    }
}
